import Head from 'next/head'
import '../styles/globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { ChakraProvider } from "@chakra-ui/react"


function MyApp({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>PDFTron Reservation System</title>
                <meta name="description" content="Generated by create next app"
                    key="title" />
                <link rel="icon" href="/pdftron-icons/PDFtron.ico" />
            </Head>
            <ChakraProvider>
                <Component {...pageProps} />
            </ChakraProvider>
        </>
    )
}

export default MyApp
