import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
      <Head>
        <title>PDFTron Reservation System</title>
        <meta name="description" content="Generated by create next app" key="title"/>
        <link rel="icon" href="/pdftron-icons/PDFtron.ico" />
      </Head>
  )
}


